name: Build and deploy ASP.Net Core app to Azure Web App - BlazorAndAzureCICD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build the Web App project
      - name: Build Web App
        run: dotnet build BlazorAndAzureCICD/BlazorAndAzureCICD.csproj --configuration Release

      # Build the Client project
      - name: Build Client Project
        run: dotnet build BlazorAndAzureCICD.Client/BlazorAndAzureCICD.Client.csproj --configuration Release

      # Publish the Web App project
      - name: Publish Web App
        run: dotnet publish BlazorAndAzureCICD/BlazorAndAzureCICD.csproj --configuration Release -o publish\web

      # Publish the Client project
      - name: Publish Client Project
        run: dotnet publish BlazorAndAzureCICD.Client/BlazorAndAzureCICD.Client.csproj --configuration Release -o publish\client

      # (Optional) Merge Client publish output into Web App's publish folder if required by your deployment
      - name: Merge Publish Outputs
        run: |
          # This command copies the client output into a "Client" subfolder inside the web publish folder.
          xcopy /E /I /Y publish\client publish\web\Client

      # Upload the merged artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish\web

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D420E5E30CD345DABE9261B31E9C42E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C57258D964C1465289B783FB82637239 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D1CAC873CEF465192614099FF602048 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BlazorAndAzureCICD'
          slot-name: 'Production'
          package: .
